name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write 

jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Git config
      run: |
        git config --global user.name "Weily Huang"
        git config --global user.email "w3ily10@gmail.com"
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Build Vue 3 app
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./dist
    - name: Start Vue 3 app 
      run: npm run dev > server.log 2>&1 &
    - name: Upload server logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-log
        path: server.log
    - name: Wait for Vue app to be available
      run: npx wait-on http://localhost:5173/
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  deploy:
    timeout-minutes: 10
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: ./dist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist